UniqueNetwork/unique-explorer-api

- docker/polkastats-backend/sql/polkastats.sql
- lib/utils.js
FIX: Fixed crawler for collections
> NFTPAR-779 to develop

- crawlers/collectionListener.js
> NFTPAR-820 to develop

- package.json
- Updated package.json;
- Added protobufjs to package.json;
> Added protobuf.js

- sequelize/migrations/20211111142420-view_transfer.js
feat: NFTPAR-821 View hash
- Added migration to create view 'view_transfer';
Jira issue [NFTPAR-821]
> NFTPAR-821 to develop

- config/config.js
Closes #ISSUE
**Description:**
Thank you! 🚀
---
For contributor:
For reviewer:
> Revert config;

- crawlers/tokenListener.js
- lib/eventFactory.js
- lib/eventFactory/eventCollection.js
- lib/eventFactory/eventToken.js
- lib/eventFactory/events.js
- lib/providerAPI/api.js
- lib/providerAPI/bridgeProviderAPI/abstractAPI.js
- lib/providerAPI/bridgeProviderAPI/concrete/opalAPI.js
- lib/providerAPI/bridgeProviderAPI/implementorAPI.js
- lib/providerAPI/bridgeProviderAPI/opalAPI.js
- lib/providerAPI/bridgeProviderAPI/testnetAPI.js
- lib/tokenData.js
- package.json
refactor: NFTPAR-873
- Replaced api on bridgeAPI in tokenData, tokenListener;
- Added method getToken to abstractAPI;
- Realized method `getToken` to opalAPI and testnetAPI;
- Replaced api on bridgeAPI in eventFactory, eventCollection, events and
etc;
Jira issue: [NFTPAR-873]
> NFTPAR-873 to develop

- lib/extrinsicDB.js
- lib/extrinsicData.js
- utils/utils.js
refactor: NFTPAR-873
- Added extrinsicsDB.js and extrinsicData.js;
- Added condition for `setValidationData` to `utils.js` for
`extrinsics`;
Issue Jira [NFTPAR-873]
> NFTPAR-872 to develop

- crawlers/blockListener.js
- crawlers/oldBlockListener.js
- lib/blockDB.js
- lib/blockData.js
- lib/eventsDB.js
- lib/eventsData.js
feat: NFTPAR-861
- Added `CRAWLER_OLD_BLOCK_LISTENER_DISABLE` to env;
- Refactoring `blockListener`;
Jira issue [NFTPAR-861]
> NFTPAR-861 to develop

- crawlers/blockListener.js
- crawlers/eventFacade.js
- lib/eventFactory.js
- lib/eventFactory/createCollection.js
- lib/eventFactory/eventToken.js
- lib/eventFactory/events.js
- lib/tokenDB.js
- lib/tokenData.js
- package.json
- Fixed events for collection;
- Fixed evnets for create tokens;
Closes #ISSUE
**Description:**
Thank you! 🚀
---
For contributor:
For reviewer:
> fix: Don't create collection when event listener

- crawlers/tokenListener.js
- lib/api.js
- lib/providerAPI/bridgeProviderAPI/concreate/abstractAPI.js
- lib/providerAPI/bridgeProviderAPI/concreate/opalAPI.js
- lib/providerAPI/bridgeProviderAPI/concreate/testnetAPI.js
- lib/providerAPI/bridgeProviderAPI/implement/implementOpalAPI.js
- lib/providerAPI/bridgeProviderAPI/implement/implementorAPI.js
- lib/providerAPI/bridgeProviderAPI/implement/implemnetTestnetAPI.js
feat: NFTPAR-912
- Modified method for token in implemnetOpalApi;
Jira issue [NFTPAR-912]
> NFTPAR-912 to develop

- crawlers/collectionListener.js
fix: NFTPAR-919
- Added drop for collection. If collection is not exists then collection droped
Jira issue [NFTPAR-919]
> NFTPAR-919 to develop

- lib/eventFactory.js
- lib/eventsData.js
- lib/extrinsicData.js
- sequelize/migrations/20211228102209-view_extrisic.js
fix: NFTPAR-1046
Updated bignumber;
Jira issue: NFTPAR-1046
> NFTPAR-1046 to develop

- config/config.js
- crawlers/oldBlockListener.js
- sequelize/migrations/20211229153046-view_event_amount.js
- utils/utils.js
fix: NFTPAR-1075
- Added a first_block;
> NFTPAR-1075 to develop

- crawlers/oldBlockListener.js
- lib/blockDB.js
> NFTPAR-491 to develop

- lib/blockDB.js
- package.json
- sequelize/migrations/20211229153046-view_event_amount.js
- sequelize/migrations/20220116194628-view_tokens_and_collections.js
feat: NFTPAR-1104
- Added view for collections and tokens;
Jira issue [NFTPAR-1104]
> NFTPAR-1104 to develop

- package.json
- sequelize/migrations/20220124101719-alter-event-add-indexes.js
- sequelize/migrations/20220124140110-alter-view_events.js
Fix performance for query from view `view_extrinsic`.
> NFTPAR-1146 view_extrinsic performance

- sequelize/migrations/20220127095207-alter-view_tokens.js
New column was added into view.
> NFTPAR-1171 new columns for view_tokens

- crawlers/blockListener.js
- crawlers/eventFacade.js
- lib/collectionDB.js
- lib/collectionData.js
- lib/collectionsStatsDB.js
- lib/eventFactory.js
- lib/eventFactory/collection/createCollection.js
- lib/eventFactory/eventCollection.js
- lib/eventFactory/eventToken.js
- lib/eventFactory/token/createToken.js
- lib/eventFactory/token/destroyedToken.js
- lib/eventsDB.js
- lib/tokenDB.js
- sequelize/migrations/20220127123049-collections-add-column-mint_mode.js
- sequelize/migrations/20220131100326-create-table-collections_stats.js
- sequelize/migrations/20220202100349-collections-add-column-date_of_creation.js
- sequelize/migrations/20220202100725-tokens-add-column-date_of_creation.js
- sequelize/migrations/20220203094434-filling-collections_stats.js
- sequelize/migrations/20220203102358-alter-view_collections.js
Save statistic for collections by events  in special table. Added statistics fields to view_collections.
> NFTPAR-1171 statistic for collection

- .github/workflows/deploy-to-develop.yml
- .github/workflows/deploy-to-stage.yml
Closes #ISSUE
**Description:**
Thank you! 🚀
---
For contributor:
For reviewer:
> [Flant] 336722 add deploy to dev and stage from gitlab

- lib/collectionData.js
- package.json
- sequelize/migrations/20220305153849-remove-extrinsic_args_idx.js
Converting sponsor rate limit was fixed.
Fix for incorrect column index.
> Fix collection converting limits_sponsore_data_rate

- sequelize/migrations/20220525090639-add-token-name-into-view-tokens.js
Closes #IWMS-984
Added token_name field into view_tokens view.
> Added token_name field into view_tokens view

- crawlers/crawlers.ts
- sequelize/migrations/20220527032415-view_events-and-view_extrinsic-rework.js
> feature/wms-886, Views rework migration

- crawlers/activeAccounts.ts
> WMS-902 Fix locked balance calculation

- lib/collection/collectionData.ts
- lib/collection/collectionDbEntity.interface.ts
- sequelize/migrations/20220614042733-update-collection-owner_can-columns.js
> Update collections.owner_can_* columns

- lib/collection/collectionDb.ts
- lib/eventFactory/token/EventToken.ts
> Token date of creation fix

- config/config.ts
- lib/collection/collectionData.ts
- lib/providerAPI/providerAPI.ts
> collection_cover value calculation rework

- crawlers/collectionsScanner.ts
- crawlers/tokensScanner.ts
- lib/collection/collectionData.ts
- lib/eventFactory/collection/EventCollection.ts
- lib/eventFactory/token/EventToken.ts
- lib/providerAPI/bridgeApi.ts
- lib/providerAPI/bridgeProviderAPI/concreate/abstractAPI.ts
- lib/providerAPI/bridgeProviderAPI/concreate/opalAPI.ts
- lib/providerAPI/bridgeProviderAPI/concreate/testnetAPI.ts
- lib/providerAPI/bridgeProviderAPI/implement/implementOpalAPI.ts
- lib/providerAPI/bridgeProviderAPI/implement/implementorAPI.ts
- lib/providerAPI/bridgeProviderAPI/implement/implemnetTestnetAPI.ts
> Using effectiveCollectionLimits api method
